<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Corporation;
use Doctrine\ORM\EntityRepository;

/**
 * BuybackConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuybackConfigurationRepository extends EntityRepository
{

    public function findConfigByType(Corporation $corp, $type){
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.corporation = :corp')
            ->andWhere('c.type = :type')
            ->setParameters(['corp' => $corp, 'type' => $type])
            ->getQuery()->getResult();
    }
}
