<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Corporation;
use Doctrine\ORM\EntityRepository;

/**
 * MarketOrderGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketOrderGroupRepository extends EntityRepository
{
     public function getLatestMarketOrderGroup(Corporation $entity){

        return $this->createQueryBuilder('ag')
            ->select('ag')
            ->where('ag.corporation = :corporation')
            ->orderBy('ag.created_at', 'DESC')
            ->setMaxResults(1)
            ->setParameter('corporation', $entity)
            ->getQuery()->getOneOrNullResult();

    }
}
