<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTypeRepository extends EntityRepository
{

    public function getRefTypeIds(){
        $data = $this->createQueryBuilder('rt')
            ->select('rt')
            ->groupBy('rt.ref_type_id')
            ->getQuery()->getResult();

        return $data;
    }
}
