<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTypeRepository extends EntityRepository
{

    public function getRefTypeIds(){
        return $this->createQueryBuilder('rt')
            ->select('rt.ref_type_id')
            ->getQuery()->getResult();
    }
}
