<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Corporation;
use Doctrine\ORM\EntityRepository;

/**
 * StarBaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarBaseRepository extends EntityRepository
{
    public function hasPOS(Corporation $corp, $moonId)
    {
        return $this->createQueryBuilder('sb')
            ->select('sb')
            ->where('sb.corporation = :corp')
            ->andWhere('sb.moon_id = :moon_id')
            ->setParameters([
                'corp' => $corp,
                'moon_id' => $moonId,
            ])
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
    }
}
